[parameters]
blah = "blah"
Sns1 = "sns1"
Sns2 = "sns2"

#[templates.example1]
#name = "hello1"
#path = "tpls/example.yml"

[templates.example2]
name = "hello2"
path = "tpls/example2.yml"

[templates.example2.parameters]
Sns2 = "foo"
