[parameters]
blah = "blah"
Sns1 = "sns1"
Sns2 = "sns2"

region = "eu-west-1"
profile = "meadmin"

[stacks.example1]
name = "hello1"
path = "tpls/example.yml"
blocked = ["SNSTopic"]

[stacks.example2]
name = "hello2"
path = "tpls/example2.yml"

[stacks.example2.parameters]
Sns2 = "foo"
